set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A Smart IDE written by Qt")
set(CPACK_PACKAGE_VENDOR "Kreogist Dev Team")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${}/README.md")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/licenses/LICENSE_GPL.rtf")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "2")
set(CPACK_PACKAGE_VERSION_PATCH "1.0")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Kreogist/${PROJECT_NAME}.${CPACK_PACKAGE_VERSION_MAJOR}")

if(CPACK_GENERATOR MATCHES "NSIS")

endif()

if(CPACK_GENERATOR MATCHES "DEB")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libstdc++6 (>=4.4.0), libqt5core5 (>= 5.2.0), libqt5gui5 (>= 5.2.0), libqt5widgets5 (>= 5.2.0)")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Wang Luming<wlm199558@126.com>")
endif()